name: C/C++ CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  workflow_dispatch:

env:
  # Customize the CMake build type here (Release, Debug, RelWithDebInfo, etc.)
  BUILD_TYPE: RelWithDebInfo

jobs:
  test:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      with:
        submodules: True
      
    - name: Create Build Environment
      run: cmake -E make_directory ${{runner.workspace}}/build
      
    

    - name: Test python bindings
      working-directory: $GITHUB_WORKSPACE
      shell: bash
      run: pwd && ls -la && python3 --version && python3 setup.py test
      
